test:
#  hostport: localhost:20001
  uri: lb://backend-server
#  hostport: httpbin.org:80
#  hostport: localhost:20001
#  uri: http://${test.hostport}
#  uri: lb://httpbin

spring:
  jmx:
    enabled: false
  cloud:
    gateway:
#      default-filters:
#      - PrefixPath=/httpbin
#      - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      # =====================================
      # to run server
      # $ wscat --listen 9000
      # to run client
      # $ wscat --connect ws://localhost:8080/echo
#      - id: websocket_test
#        uri: ws://localhost:9000
#        order: 9000
#        predicates:
#        - Path=/echo
      # =====================================
      - id: backend-server
        uri: ${test.uri}
        order: 10000
        predicates:
        - Path=/backend-server/**
        filters:
        - PreserveHostHeader
  application:
    name: gateway-server

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
server:
  port: 20002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:18080/eureka
  instance:
    prefer-ip-address: true
debug: true

